CREATE TABLE facts(
    factsID SERIAL NOT NULL PRIMARY KEY,
    dateCreated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    data JSON NOT NULL
);

CREATE OR REPLACE FUNCTION trigger_set_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_timestamp
BEFORE UPDATE ON facts
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_timestamp();