---
    -   name: nexus add vlan playbook
        connection: local
        gather_facts: false
        hosts:
            -   nexus

        tasks:
            -   name: parse incoming configuration
                set_fact:
                    in_cfg: "{{jsonString | from_json}}"

            -   name: add vlan to trunk interface by merging with old device configuration
                nxos_l2_interfaces:
                    config:
                    -   name: "{{item | string}}"
                        access:
                            vlan: "{{in_cfg['vlan'] | int}}"
                    state: merged
                with_items:
                    - "{{in_cfg['interfaces'] | liist}}"
                when:
                    -   ansible_network_os == "nxos"