---
    -   name: nexus add vlan playbook
        connection: local
        gather_facts: false
        hosts:
            -   nexus

        tasks:
            -   name: read config file
                set_fact:
                    in_cfg: "{{ lookup('file','../../temp/config.json') | from_json }}"

            -   name: add vlan to trunk interface by merging with old device configuration
                nxos_l2_interfaces:
                    config:
                    -   name: "{{item | string}}"
                        trunk:
                            allowed_vlans: "{{in_cfg['interfaces']['trunk_interfaces'][item]['allowed_vlans']}}"
                            native_vlan: "{{in_cfg['interfaces']['trunk_interfaces'][item]['native_vlan']}}"
                    state: merged
                with_items:
                    - "{{in_cfg['interfaces']['trunk_interfaces'] | list}}"
                when:
                    -   ansible_network_os == "nxos"