---

    -   name: nexus add vlan playbook
        connection: local
        gather_facts: false
        hosts:
            -   nexus
        
        tasks:

            -   name: read config file
                set_fact:
                    in_cfg: "{{ lookup('file','../../temp/config.json') | from_json }}"

            -   name: debug
                debug:
                    msg: "{{in_cfg}}"

            -   name: merge provided configuration with device configuration
                nxos_vlans:
                    config:
                        -   vlan_id: "{{in_cfg['vlan'] | int}}"
                            name: "{{in_cfg['vlan_name'] | string}}"
                            state: active
                    state: merged
                when:
                    -   in_cfg['hosts'][inventory_hostname] is defined