---
    -   name: nexus add vlan playbook
        connection: local
        gather_facts: false
        hosts: "{{h}}"

        tasks:
            -   name: parse incoming configuration
                set_fact:
                    in_cfg: "{{cmd | from_json }}"

            -   name: merge provided configuratioin with device configuratioin
                nxos_vlans:
                    config:
                        -   vlan_id: "{{in_cfg['vlan'] | int}}"
                            name: "{{in_cfg['vlanName'] | string}}"
                            state: active
                    state: merged
                when:
                    -   ansible_network_os == "nxos"